# Generated by Django 4.2.30 on 2026-06-24 00:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='decoys',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Decoys'),
        ),
        migrations.AddField(
            model_name='play',
            name='flashbangs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Flashbangs'),
        ),
        migrations.AddField(
            model_name='play',
            name='he_grenades',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='HE Grenades'),
        ),
        migrations.AddField(
            model_name='play',
            name='molotovs',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Molotovs/Incendiárias'),
        ),
        migrations.AddField(
            model_name='play',
            name='players_required',
            field=models.PositiveSmallIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='play',
            name='smokes',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Smokes'),
        ),
        migrations.AddField(
            model_name='play',
            name='video_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
