# Generated by Django 4.2.30 on 2026-06-24 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0002_play_decoys_play_flashbangs_play_he_grenades_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='play',
            name='players_required',
            field=models.PositiveSmallIntegerField(default=1),
        ),
    ]
