# Generated by Django 4.2.30 on 2026-06-25 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plays', '0003_alter_play_players_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='play',
            name='map',
            field=models.CharField(blank=True, choices=[('mirage', 'Mirage'), ('inferno', 'Inferno'), ('dust2', 'Dust 2'), ('nuke', 'Nuke'), ('overpass', 'Overpass'), ('ancient', 'Ancient'), ('anubis', 'Anubis'), ('vertigo', 'Vertigo'), ('train', 'Train')], max_length=20),
        ),
    ]
